apiVersion: v1
kind: Service
metadata:
  name: ChatSarathi-backend
spec:
  type: LoadBalancer
  selector:
    app: ChatSarathi-backend
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: ChatSarathi-redis
spec:
  selector:
    app: ChatSarathi-redis
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ChatSarathi-backend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ChatSarathi-backend
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
